### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by chrislusf** [smiller123/bento#3]
After git cloning the project on a linux env, a "make" inside "bentofs" directory fails. I wonder what should be changed here:

```
chrislu@chrislu-VirtualBox:~/dev/bento$ ls -al
total 84
drwxrwxr-x 15 chrislu chrislu 4096 Jan 28 00:57 .
drwxrwxr-x  5 chrislu chrislu 4096 Jan 18 23:52 ..
drwxrwxr-x  3 chrislu chrislu 4096 Jan 18 23:52 bento
drwxrwxr-x  2 chrislu chrislu 4096 Jan 28 01:17 bentofs
drwxrwxr-x  3 chrislu chrislu 4096 Jan 18 23:52 bento_utils
drwxrwxr-x  5 chrislu chrislu 4096 Jan 18 23:52 datablock-rs
drwxrwxr-x  9 chrislu chrislu 4096 Jan 18 23:52 .git
-rw-rw-r--  1 chrislu chrislu 4628 Jan 18 23:52 .gitlab-ci.yml
-rw-rw-r--  1 chrislu chrislu  192 Jan 18 23:52 .gitmodules
drwxrwxr-x  3 chrislu chrislu 4096 Jan 18 23:52 hello_client
drwxrwxr-x  3 chrislu chrislu 4096 Jan 18 23:52 hello_ll
drwxrwxr-x  3 chrislu chrislu 4096 Jan 18 23:52 hello_ll2
drwxrwxr-x  3 chrislu chrislu 4096 Jan 18 23:52 hello_srv
-rw-rw-r--  1 chrislu chrislu  337 Jan 18 23:52 LICENSE
-rw-rw-r--  1 chrislu chrislu 5017 Jan 18 23:52 README.md
drwxrwxr-x  2 chrislu chrislu 4096 Jan 28 00:57 .vscode
drwxrwxr-x  4 chrislu chrislu 4096 Jan 18 23:52 xv6fs
drwxrwxr-x  3 chrislu chrislu 4096 Jan 18 23:52 xv6fs2
drwxrwxr-x  5 chrislu chrislu 4096 Jan 18 23:52 xv6fs_prov
chrislu@chrislu-VirtualBox:~/dev/bento$ cd bentofs/
chrislu@chrislu-VirtualBox:~/dev/bento/bentofs$ make
make -C /lib/modules/5.11.0-46-generic/build M=/home/chrislu/dev/bento/bentofs modules
make[1]: Entering directory '/usr/src/linux-headers-5.11.0-46-generic'
  CC [M]  /home/chrislu/dev/bento/bentofs/dir.o
/home/chrislu/dev/bento/bentofs/dir.c: In function ‘bento_create_open’:
/home/chrislu/dev/bento/bentofs/dir.c:452:8: error: too many arguments to function ‘finish_open’
  452 |  err = finish_open(file, entry, generic_file_open, opened);
      |        ^~~~~~~~~~~
In file included from /home/chrislu/dev/bento/bentofs/bento_i.h:16,
                 from /home/chrislu/dev/bento/bentofs/dir.c:11:
./include/linux/fs.h:2553:12: note: declared here
 2553 | extern int finish_open(struct file *file, struct dentry *dentry,
      |            ^~~~~~~~~~~
/home/chrislu/dev/bento/bentofs/dir.c: In function ‘bento_atomic_open’:
/home/chrislu/dev/bento/bentofs/dir.c:491:13: error: ‘FILE_CREATED’ undeclared (first use in this function); did you mean ‘FUSE_CREATE’?
  491 |  *opened |= FILE_CREATED;
      |             ^~~~~~~~~~~~
      |             FUSE_CREATE
/home/chrislu/dev/bento/bentofs/dir.c:491:13: note: each undeclared identifier is reported only once for each function it appears in
/home/chrislu/dev/bento/bentofs/dir.c: In function ‘create_new_entry’:
/home/chrislu/dev/bento/bentofs/dir.c:565:8: error: implicit declaration of function ‘d_instantiate_no_diralias’ [-Werror=implicit-function-declaration]
  565 |  err = d_instantiate_no_diralias(entry, inode);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/chrislu/dev/bento/bentofs/dir.c: At top level:
/home/chrislu/dev/bento/bentofs/dir.c:1676:17: error: initialization of ‘int (*)(struct inode *, struct dentry *, struct file *, unsigned int,  umode_t)’ {aka ‘int (*)(struct inode *, struct dentry *, struct file *, unsigned int,  short unsigned int)’} from incompatible pointer type ‘int (*)(struct inode *, struct dentry *, struct file *, unsigned int,  umode_t,  int *)’ {aka ‘int (*)(struct inode *, struct dentry *, struct file *, unsigned int,  short unsigned int,  int *)’} [-Werror=incompatible-pointer-types]
 1676 |  .atomic_open = bento_atomic_open,
      |                 ^~~~~~~~~~~~~~~~~
/home/chrislu/dev/bento/bentofs/dir.c:1676:17: note: (near initialization for ‘bento_dir_inode_operations.atomic_open’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:288: /home/chrislu/dev/bento/bentofs/dir.o] Error 1
make[1]: *** [Makefile:1849: /home/chrislu/dev/bento/bentofs] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-46-generic'
make: *** [Makefile:5: all] Error 2

```

**Comment by chrislusf** [comment]
Seems the "5.11.0-46-generic" is too new. May need a different branch for it.

**Comment by smiller123** [comment]
Yes. The main branch is for 4.15. There's a branch called linux-5.4 on that repo that may work for you. I can also update it to work with 5.11 if that's what you'll be using.

This repo's main branch is also written for 4.15. There's also a 5.11 branch on this repo that may work for you. I haven't looked at it in a while though, so I'm not totally positive. Let me know if anything isn't working on any branch, and I can update it to work.

**Comment by chrislusf** [comment]
Thanks! Using 5.11 worked!
